config/routes.rb
Rails.application.routes.draw do
  get 'items/index'

  get 'items/show'

  get 'items/new'

  get 'items/edit'

  root 'lists#index'

  resources :lists
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items, dependent: :destroy

	validates_presence_of :name
	validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		redirect_to item_path(@item)
  	else
  		render :edit
  	end
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
  	if @item.save
  		redirect_to items_path
  	else
  		render :new
  	end
  end

  def destroy
  	Item.find(params[:id]).destroy
  	redirect_to items_path
  end

  private

  def item_params
  	params.require(:item).permit(:name, :description, :complete)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  	@lists = List.all
  end

  def show
  	@list = List.find(params[:id])
  end

  def edit
  	@list = List.find(params[:id])
  end

  def update
  	@list = List.find(params[:id])
  	if @list.update(list_params)
  		redirect_to list_path(@list)
  	else
  		render :edit
  	end
  end

  def new
  	@list = List.new
  end

  def create
  	@list = List.new(list_params)
  	if @list.save
  		redirect_to lists_path
  	else
  		render :new
  	end
  end

  def destroy
  	List.find(params[:id]).destroy
  	redirect_to lists_path
  end

  private

  def list_params
  	params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.label :complete %>
	<%= f.boolean :complete %>

	<%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item: <%= @item.name %></h1>
<br />

<%= render(partial: 'form') %>

app/views/items/index.html.erb
<h1>All Items</h1>
<br />

<% if @items.any? %>
	<ul>
		<% @items.each do |item| %>
			<li>
				<%= link_to item.name, item_path(item) %>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No items found. Please create one!</h3>
<% end %>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>Create a New Item</h1>
<br />

<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<br />
<h3><%= @item.description %>
<h3><%= @item.complete %>

<%= link_to 'Edit', edit_item_path(@item) %>

<%= link_to 'Delete', item_path(@item), method: :delete %>

<%= link_to 'All Items', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List: <%= @list.name %></h1>
<br />

<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<br />
<% if @lists.any? %>
	<ul>
		<% @lists.each do |list| %>
			<li>
				<%= link_to list.name, list_path(list) %>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No lists found. Please create one!</h3>
<% end %>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>Create a New To Do List</h1>
<br />

<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<h1><%= @list.name %> </h1>
<br />

<%= link_to 'Edit', edit_list_path(@list) %>

<%= link_to 'Delete', list_path(@list), method: :delete %>

<%= link_to 'All Lists', lists_path %>